version: '2'
services:
    cool_pass-app:
        image: cool_pass
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cool_pass-mysql:3306/cool_pass?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cool_pass-mysql:
        extends:
            file: mysql.yml
            service: cool_pass-mysql
